language: android

android:
  components:
    - build-tools-21.1.1
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-preview-license-52d11cd2

branches:
  except:
    - gh-pages

notifications:
  email: false

before_install:
 - ./check-missing-assertions.sh

script:
 - ./gradlew clean check
